HCRMtxCfg <- list()

# ------------------------------------------------------------------------------------------
#   szMtx for bFMtx (Ph,fCol)
# ------------------------------------------------------------------------------------------
mName <- "HCRsz_bf01Ph"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score1"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score2"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score3"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"score5"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score8"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score9"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bf2APh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
             "score4"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score6"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score7"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreA"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreB"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreC"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreD"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreE"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreF"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bfavPh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
             "scoreLAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreLAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bf01fCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score1"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,1,3,3),c(1,1,3,4)) ,ncol=2)
                        ) 
            ,"score2"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score3"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score5"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score8"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score9"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bf2AfCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
             "score4"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score6"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score7"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreA"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreB"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreC"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreD"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreE"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreF"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bfavfCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
             "scoreLAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreLAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}

# ------------------------------------------------------------------------------------------
#   szMtx for bSMtx (Ph,fCol)
# ------------------------------------------------------------------------------------------
mName <- "HCRsz_bS01Ph"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore05"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore08"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore09"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=2 ,lowE=2,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bS2APh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore04"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore06"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore07"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=3 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bSavPh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore0LAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore0LAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=2 ,lowE=3 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bS1avPh"    # bS01Ph + bSavPh
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore05"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)   #
                        )
            ,"sScore08"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore09"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)   #
                        )
            ,"sScore0LAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore0LAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=2 ,lowE=2 ,rareE=1 ,dupESum=2 )
                # 812 825 838 853 reb(1)
        ,isHard=NULL  # use default
    )

}
mName <- "HCRsz_bS01AVefCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore05"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"sScore08"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore09"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=2,rareE=1 ,dupESum=2 )  # freqVal로 처리하긴 했는데... rawWin=2이 나으려나?
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bS2AfCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore04"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore06"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore07"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=2,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bSavfCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "sScore0LAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore0LAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=2,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}



# ------------------------------------------------------------------------------------------
#   szMtx for bfMtx + bSMtx (Ph,fCol)
# ------------------------------------------------------------------------------------------
mName <- "HCRsz_bfS01Ph"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score1"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score2"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score3"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"score5"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score8"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score9"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore05"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore08"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore09"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfS2APh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score4"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score6"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score7"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreA"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreB"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreC"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreD"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreE"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            ,freqVal=c(1)
                        )
            ,"scoreF"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore04"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore06"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore07"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            # ,"scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfSAVePh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )  # H853 H884
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfSavPh"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "scoreLAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )

            ,"sScore0LAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}

mName <- "HCRsz_bfS01fCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score1"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,1,3,3),c(1,2,3,4)) ,ncol=2)  # 
                        ) 
            ,"score2"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(3,3,3),c(2,3,4)) ,ncol=2)  # 
                        )
            ,"score3"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score5"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score8"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score9"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore01"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"sScore02"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore03"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore05"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore08"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore09"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfS2AfCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score4"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score6"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score7"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreA"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreB"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreC"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreD"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreE"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                            # ,freqVal=c(1)
                        )
            ,"scoreF"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore04"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore06"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore07"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            # ,"scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
            # ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
            #                 ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
            #             )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfSAVefCol"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "scoreLAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVe24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}
mName <- "HCRsz_bfSavfCol"
if( TRUE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "scoreLAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )

            ,"sScore0LAr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVr24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVc24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LAf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf13"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"sScore0LVf24"=list( rng=matrix( c(0,0 ,0,4) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = c( rawMin=1 ,lowE=3,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )
}




# ------------------------------------------------------------------------------------------
#   szMtx for bFMtx reb (r.ph,r.fCol,r.dblHpnFlg)       HCR.MtxTmpl_rebSz()
# ------------------------------------------------------------------------------------------
mName <- "HCRreb_szC01R"    # HCRreb_szC는 발생 자체가 희귀하긴 하다.
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score1"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score2"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score3"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score5"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL
        ,isHard=NULL  # use default
    )

}

mName <- "HCRreb_szC02R"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "score4"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"score6"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score7"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score8"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"score9"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL
        ,isHard=NULL  # use default
    )

}

mName <- "HCRreb_szCAavR"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
            "scoreA"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreB"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreC"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreD"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreE"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreF"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe13"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAe24"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe13"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVe24"=list( rng=matrix( c(0,0 ,0,1) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL
        ,isHard=NULL  # use default
    )

}

mName <- "HCRreb_szCavR"
if( FALSE ){ # done. OK
    HCRMtxCfg[[mName]] <- list(
        mName = mName   ,style=c( freqZero=TRUE )
        ,fCol = list(
             "scoreLAr13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        ) 
            ,"scoreLAr24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVr24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAc24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVc24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLAf24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf13"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
            ,"scoreLVf24"=list( rng=matrix( c(0,0 ,0,0) ,ncol=2 )
                            ,evt=matrix( c(c(1,3,3,3),c(1,2,3,4)) ,ncol=2)
                        )
        )
        ,evtMax = NULL
        ,rowReb = NULL  # c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
        ,isHard=NULL  # use default
    )

}





for( mName in names( HCRMtxCfg ) ){

    for( fcName in names(HCRMtxCfg[[mName]]$fCol) ){
        colnames(HCRMtxCfg[[mName]]$fCol[[fcName]]$rng) <- c("lev1","lev2")
        rownames(HCRMtxCfg[[mName]]$fCol[[fcName]]$rng) <- c("min","max")

        colnames(HCRMtxCfg[[mName]]$fCol[[fcName]]$evt) <- c("lev","val")

        # ,forbidEvtReb=c(2,3) ,freqVal=c(1,2)
        if( is.null(HCRMtxCfg[[mName]]$fCol[[fcName]]$forbidEvtReb) ){
            HCRMtxCfg[[mName]]$fCol[[fcName]]$forbidEvtReb <- c(2,3,4)
        }
    }

    if( is.null(HCRMtxCfg[[mName]]$evtMax) ){
        #   이벤트 발생 제한.
        #   "minLev"이상 이벤트가 maxHpn 보다 초과할 때 Cut
        HCRMtxCfg[[mName]]$evtMax = matrix( c(2,2,3,1 ,2,3,3,2)     ,byrow=T ,ncol=4
                            ,dimnames=list(c("lev1","lev2"),c("minLev","maxHpn","minLevH","maxHpnH")) 
        )
    }
    if( is.null(HCRMtxCfg[[mName]]$rowReb) ){
        HCRMtxCfg[[mName]]$rowReb = c( rawMin=1 ,lowE=2 ,rareE=1 ,dupESum=2 )
    }

}
